include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - prefer_const_constructors
    - prefer_const_literals_to_create_immutables
    - prefer_const_constructors_in_immutables
    - avoid_print: false
    - prefer_single_quotes: true
    - always_declare_return_types: true
    - annotate_overrides: true
    - avoid_empty_else: true
    - avoid_init_to_null: true
    - avoid_returning_null_for_void: true
    - avoid_types_as_parameter_names: true
    - camel_case_types: true
    - cancel_subscriptions: true
    - close_sinks: true
    - comment_references: true
    - constant_identifier_names: true
    - control_flow_in_finally: true
    - empty_catches: true
    - empty_constructor_bodies: true
    - library_names: true
    - library_prefixes: true
    - no_duplicate_case_values: true
    - null_closures: true
    - prefer_contains: true
    - prefer_equal_for_default_values: true
    - prefer_final_fields: true
    - prefer_initializing_formals: true
    - prefer_is_empty: true
    - prefer_is_not_empty: true
    - prefer_iterable_whereType: true
    - prefer_typing_uninitialized_variables: true
    - recursive_getters: true
    - slash_for_doc_comments: true
    - test_types_in_equals: true
    - throw_in_finally: true
    - type_init_formals: true
    - unnecessary_brace_in_string_interps: true
    - unnecessary_const: true
    - unnecessary_new: true
    - unnecessary_null_in_if_null_operators: true
    - unnecessary_this: true
    - unrelated_type_equality_checks: true
    - use_rethrow_when_possible: true
    - valid_regexps: true

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"

