name: Build Android APK

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: # 允许手动触发

jobs:
  build-android:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'
        
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.35.5'
        channel: 'stable'
        
    - name: Get dependencies
      run: |
        cd flutter_app
        flutter pub get
        
    - name: Run tests
      run: |
        cd flutter_app
        flutter test --no-pub
      continue-on-error: true
        
    - name: Build Universal APK
      run: |
        cd flutter_app
        flutter build apk --release
        
    - name: Build Split APKs (per architecture)
      run: |
        cd flutter_app
        flutter build apk --release --split-per-abi
        
    - name: Upload APKs
      uses: actions/upload-artifact@v4
      with:
        name: android-apks
        path: |
          flutter_app/build/app/outputs/flutter-apk/app-release.apk
          flutter_app/build/app/outputs/flutter-apk/app-arm64-v8a-release.apk
          flutter_app/build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk
          flutter_app/build/app/outputs/flutter-apk/app-x86_64-release.apk
        
    - name: Create Draft Release (on main branch)
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      uses: softprops/action-gh-release@v1
      with:
        files: |
          flutter_app/build/app/outputs/flutter-apk/app-release.apk
          flutter_app/build/app/outputs/flutter-apk/app-arm64-v8a-release.apk
          flutter_app/build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk
          flutter_app/build/app/outputs/flutter-apk/app-x86_64-release.apk
        generate_release_notes: true
        draft: true
        prerelease: true
        tag_name: "build-${{ github.run_number }}"
        name: "Build ${{ github.run_number }}"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
