name: Release Android APK

on:
  push:
    tags:
      - 'v*'  # 当推送版本标签时触发
  workflow_dispatch: # 手动触发

jobs:
  release-android:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'
        
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.35.5'
        channel: 'stable'
        
    - name: Get dependencies
      run: |
        cd flutter_app
        flutter pub get
        
    - name: Run tests
      run: |
        cd flutter_app
        flutter test --no-pub
      continue-on-error: true
        
    - name: Build Universal APK
      run: |
        cd flutter_app
        flutter build apk --release
        
    - name: Build Split APKs (per architecture)
      run: |
        cd flutter_app
        flutter build apk --release --split-per-abi
        
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          flutter_app/build/app/outputs/flutter-apk/app-release.apk
          flutter_app/build/app/outputs/flutter-apk/app-arm64-v8a-release.apk
          flutter_app/build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk
          flutter_app/build/app/outputs/flutter-apk/app-x86_64-release.apk
        generate_release_notes: true
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
